#!/bin/bash 

IMG="rcs/haskell-pg:8.10.1"

HOME="/home/rcs/opt/haskell/etradejanitor"

NETWORK="pgutil_lofsrud"

# docker run --user $(id -u):$(id -g) -it --rm -v $(pwd):/home/rcs/etradejanitor $IMG 

docker run -it --rm --network $NETWORK -v $(pwd):$HOME -v /home/rcs/opt/.stack:/root/.stack -w $HOME $IMG 

exit 0

