#!/bin/bash

HOME="/home/rcs/opt/haskell/etradejanitor"

JANITOR_VER="1.4.0"

PG_VER="172.20.1.3"

NETWORK="pgutil_lofsrud"

/usr/bin/docker run --network $NETWORK --user $(id -u):$(id -g)  -i --rm -v $HOME:$HOME rcs/etradejanitor:$JANITOR_VER $PG_VER "$@"

exit 0


