#!/bin/bash

# stack build --allow-different-user --system-ghc

FILE="src/Demo.hs.x"

if [ ! -f "$FILE" ]; then
    # echo "$FILE does not exist."
    mv src/Demo.hs src/Demo.hs.x

    hpack
fi

stack build --allow-different-user 

exit 0
